### ISSUE TITLE
RFE: should be able to set a cap on zram device size

### ISSUE THREAD

**Issue by cmurf** [systemd/zram-generator#10]
This breaks out from issue 9, what is effectively a feature request to support a configurable cap on the /dev/zram device's size. That way it's more likely to get to a "one size fits all" default, for IoT, cloud, servers, and workstations. The ratio would tend to apply to the smaller RAM devices, and the cap (or max size) would tend to apply to workstations and servers.

**Comment by nabijaczleweli** [comment]
Implemented in https://github.com/systemd/zram-generator/commit/81ff19051aaca9737c354309dc3ffc55daa61f25
