### ISSUE TITLE
RFE: use zramctl to set zram device size

### ISSUE THREAD

**Issue by cmurf** [systemd/zram-generator#11]
Use zramctl instead of writing to sysfs; can also be used at some point to enable configurable compression algorithms.

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/RR3P33HSUX4XQEJ52LB3AIBYMSADTZ6I/

**Comment by keszybz** [comment]
Obsoleted by b2a7c8db000edb725b50657d8c886676e3289a77.
