### ISSUE TITLE
RFE: add support for backing device

### ISSUE THREAD

**Issue by fignew** [systemd/zram-generator#122]
From https://www.kernel.org/doc/html/latest/admin-guide/blockdev/zram.html#optional-feature

Zram can write idle/incompressible page to backing storage rather than keeping it in memory.

This is a useful feature that extends the functionality of zram and should be configurable via zram-generator.

Thanks

**Comment by keszybz** [comment]
I guess this could be done… We should extend the unit to depend on **two** devices: the zram device and the backing device. The backing device would be specified with any method supported by systemd. When the backing device appears, we would write the device path in a format that the kernel understands to /sys.
