### ISSUE TITLE
Nab's deb repo is timing out (cloudfare issue?)

### ISSUE THREAD

**Issue by eMPee584** [systemd/zram-generator#126]
Even though I can access the `InRelease` file via browser just fine (not via wget/curl though)

```
[…]
Err:19 https://debian.nabijaczleweli.xyz stable InRelease
  Connection timed out [IP: 104.21.3.191 443]
Fetched 8690 B in 30s (285 B/s)
Reading package lists...
Building dependency tree...
Reading state information...
76 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Failed to fetch https://debian.nabijaczleweli.xyz/dists/stable/InRelease  Connection timed out [IP: 104.21.3.191 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Are there any CF settings to turn off user-agent shenanigans @nabijaczleweli ?

**Comment by nabijaczleweli** [comment]
I don't think I have any on! debian.n.x *is* behind cloudflare, but AFAIK you should get you -> cloudflare [-> nginx -> http -> physical file], with the bracketed bit being in my attic. ~~I don't think filtering like this is even available on a free plan~~ free plans have UA blocking, but I have 0 rules there and all protections off.

That being said, looking at the dashboard, it looks like there's a Firewall tab now(?) and there's one request in it that would correspond temporally, I failed to find your GPG key so I posted you a mail with it, but there's one Threat, also from Germany: ![image](https://user-images.githubusercontent.com/6709544/140353827-32e160f3-a59d-4bfc-8bcc-bc048469e02b.png).

I've found a settings page with "Security Level" set to "Medium", so I set it to "Essentially Off" (fully "Off" is Enterprise), and disabled the, also new-to-me. "Browser Integrity Check" thing.

I've made an effort to disable all of these when I made the account, but more seem to've popped up. I disabled them, so this should not happen again. Thanks for bringing it up!

**Comment by nabijaczleweli** [comment]
Closing as stale

**Comment by eMPee584** [comment]
Mmh, thanks for looking at it the other day.. Still getting a time out via apt though. Direct https access and manually fetching the package works..
`W: Failed to fetch https://debian.nabijaczleweli.xyz/dists/stable/InRelease: Connection timed out [IP: 104.21.3.191 443]`

**Comment by eMPee584** [comment]
Mmmh.. the server answers from a systemd container.. but throws

```
W: GPG error: https://debian.nabijaczleweli.xyz stable InRelease: The following signatures were invalid: ERRSIG BCFD0B018D2658F1
E: The repository 'https://debian.nabijaczleweli.xyz stable InRelease' is not signed.
```

**Comment by nabijaczleweli** [comment]
The first error is an apt bug and relents when you clean out the archive cache (`apt clean`), *no* clue why (except that maybe my HTTP server responds badly, but it's to-spec, so hell if I know)!

In a bullseye chroot, running `wget -O/etc/apt/trusted.gpg.d/nabijaczleweli.asc https://debian.nabijaczleweli.xyz/nabijaczleweli.gpg.key` (or the other URL) and appending `deb https://debian.nabijaczleweli.xyz stable main` Just Works for me.

**Comment by eMPee584** [comment]
Thanks наб – removing the partial package list from `/var/lib/apt/lists/partial` indeed fixed the first problem. The second is also resolved, albeit unclear what exactly the cause.
