### ISSUE TITLE
ram size not being read from the config

### ISSUE THREAD

**Issue by KarthikNayak** [systemd/zram-generator#136]
Hello! 

I have a very minimal use case of this tool, I just want a `/dev/zram0` partition which has the same size as my ram. 
I created the config file as follows: 

```
❯ cat /etc/systemd/zram-generator.conf
[zram0]
zram-size = ram / 1
```

and followed the instructions as mentioned on the README. But it doesn't seem to be using my config. 

```
❯ free -h
               total        used        free      shared  buff/cache   available
Mem:            15Gi       1.4Gi        12Gi        46Mi       1.3Gi        13Gi
Swap:          4.0Gi          0B       4.0Gi

❯ swapon
NAME       TYPE      SIZE USED PRIO
/dev/zram0 partition   4G   0B  100
``` 

Did I miss something?

**Comment by keszybz** [comment]
Which program version are you using?

**Comment by KarthikNayak** [comment]
@keszybz 

```
❯ pacman -Qe | grep zram
zram-generator 0.3.2-1
```

**Comment by keszybz** [comment]
`zram-size` option was only added in 1.1.0. Please use `zram-fraction` and `max-zram-size` instead.

**Comment by KarthikNayak** [comment]
@keszybz thank you so much!
