### ISSUE TITLE
writeback-device option

### ISSUE THREAD

**Issue by roland-rollo** [systemd/zram-generator#139]
I have a big problem with setting the writeback-device option correctly. I uncommented `writeback-device = /dev/zvol/tarta-zoot/swap-writeback` in `/etc/systemd/zram-generator.conf` and when I restart system, it's waiting 90s and failing to create/reach this file.

If I do `cat /sys/block/zram0/backing_dev`
```
none
```

I thought files in `/dev` are created by system when its start. In zram-generator.conf man is written

> Takes a path to a block device, like /dev/disk/by-partuuid/2d54ffa0-01 or /dev/zvol/tarta-zoot/swap-writeback.

So I created block device with command
```
dd if=/dev/zero of=swap-writeback.img bs=200M count=10
```
in `/`, and created there file system `mkfs.btrfs swap-writeback.img`. But if I restart it still waiting 90s and crash.
How can I do this properly?

**Comment by keszybz** [comment]
The device must exist… `/dev/zvol/tarta-zoot/swap-writeback` is a example path to a zfs volume that most likely doesn't exist on your system.

Also, this option does not support files. It must be a device.

**Comment by nabijaczleweli** [comment]
As the documentation clearly states: you can only write-back to a block device. Do you have a block device?
From what I can tell in your comment, you (a) set the write-back device to one that doesn't exist on system (I assume you don't name your pools in polish) and (b) made an unrelated two-gigabyte file on your rootfs.
If you really want to write-back to that file, use losetup(8); otherwise, cut a zvol or make a partition on one of your disks.

**Comment by lavilao** [comment]
Can I use a swap partition as a writeback device? example:
writeback-device = /dev/sda7
Sorry if this is a stupid question

**Comment by lavilao** [comment]
Can I use a swap partition as a writeback device? example:
writeback-device = /dev/sda7
Sorry if this is a stupid question

**Comment by nabijaczleweli** [comment]
The swap signature will be erased (hopefully? I haven't tried actually, it may not get erased, or not until something gets written back, and that'd be worse); writeback excludes all other uses.

**Comment by lavilao** [comment]
shame, I was hoping giving my swap partition something useful to do
