### ISSUE TITLE
Create devices if not present?

### ISSUE THREAD

**Issue by nabijaczleweli** [systemd/zram-generator#14]
Similarly to what was causing hangs in https://github.com/systemd/zram-generator/commit/5195ea0e1f27361275db123320c3b6f1e1c32641 – by default the `zram` module creates one device (as per [sexion 1 "Load module"](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/admin-guide/blockdev/zram.rst?id=5871023c3a316e8fe8c03e7bad1d35057e69ab40)), but `swap.target` will hang indefinitely if it depends on `dev-zram1.swap`, for example.

It should be simple enough to `modprobe` and read `/sys/class/zram-control/hot_add` (sexion 7 "Add/remove zram devices") if the requisite devices are not present [here](https://github.com/nabijaczleweli/systemd-zram-generator/blob/8c83cc366b00cfd52fba3ff05c89c35fb8f00322/src/generator.rs#L49) until they become so, but that's a design decision, which I'll defer to the maintainer before implementing.

**Comment by keszybz** [comment]
I'm not sure. Would the algorithm be to read `hot_add` until we get a number great or equal to the desired device number? I guess that's an option.

**Comment by nabijaczleweli** [comment]
In essence, yes; the main problem with that is that we don't have a *time* for it.

On the generation run we might not have the module loaded yet, and when it *is* loaded we might not be invoked again because we're waiting for the setup run on, e.g. /dev/zram4 which simply isn't going to happen.

A glance at `modules-load.d(5)` doesn't reveal any way to specify any arguments for the module (like `num-devices=` for `zram`), either.

The only solution I came up with so far would be to ditch sd-modules-load and exec `modprobe zram` during the generation run instead in the `if devices_made` branch, then check if all devices we want are there and poke `hot_add` as necessary.

**Comment by nabijaczleweli** [comment]
Proposed impl in https://github.com/nabijaczleweli/systemd-zram-generator/commit/4e4859bc96db108550349b131bf1f34025420929.
