### ISSUE TITLE
Make mounted FS user writable (by setting 0777 permissions after systemd-makefs)

### ISSUE THREAD

**Issue by eMPee584** [systemd/zram-generator#146]
.. tried tagging a `DirectoryMode=0777` entry on the mount unit but as to be expected it was not enough to make the mount-point user-writable. Root access is cool already, but users want compressed temp storage as well ; )

**Comment by nabijaczleweli** [comment]
Out-of-scope, breaking, and unexpected by users IMO. You can hook this on the setup unit with an additional `ExecStart=` stanza or with the mount unit `Requires=` `After=`.

**Comment by eMPee584** [comment]
I would think many people have use for a user-writable compressed ramdisk.. I was already about to try what you suggested, but IIUsystemdC, that would need another `@service` file just for setting the mode, right? because mount units seem not to have associated commands.. And about the other option, I wouldn't know what to put in the `ExecStart` .. a command that needs to go into background, wait for makefs and mount to complete, than setting the mode. .. clumsy^^

**Comment by nabijaczleweli** [comment]
As a high-quality hack, add this as an override to the `systemd-zram-setup@.service` of your choosing: `ExecStartPost=sh -c 'd=$(mktemp -d); mount "$1" "$d"; chmod 777; umount "$d"; rm -d "$d"' _ /dev/%i`
Doing this "correctly" does require having a unit with an `After=` on the mount unit, yes.

As another point, why you'd want 777 is beyond me, but hey.

**Comment by keszybz** [comment]
I think it would make sense allow this. But I think we'd want to implement this in systemd itself: teach systemd-makefs to set owner uid, gid, mode, and possibly additonal xattrs on the root directory, then add support for passing those options in .mount units, and finally make use of this in the zram-generator.

**Comment by eMPee584** [comment]
.. thanx наб, that hack indeed fits my purpose. Filed a merge request for putting this into the dox..
