### ISSUE TITLE
writeback device - prerequisites

### ISSUE THREAD

**Issue by cmonty14** [systemd/zram-generator#163]
Hello,
according to [linux kernel guide](https://www.kernel.org/doc/html/latest/admin-guide/blockdev/zram.html) zram can write idle/incompressible page to backing storage, but it supports only partitions at this moment.

I have a partition /dev/sda2 used as swap before.

What is the prerequisite to use this partition in zram as writeback device?
Means, must I format this partition?

THX

**Comment by nabijaczleweli** [comment]
There are none, and you don't – whatever data you have there will be destroyed regardless as part of writeback.

**Comment by cmonty14** [comment]
Thanks for sharing this info.
