### ISSUE TITLE
Is it supported by systemV without using some kind of wrapper or something?

### ISSUE THREAD

**Issue by Raj2032** [systemd/zram-generator#169]
I want to install [Peppermint Devaun edition](https://peppermintos.com/guide/downloading/) which uses systemV rather than systemD, so I wanted to enquire if this is supported by systemV as well without using some kind of wrapper, as I know that with Gnome applications you have to use some kind of wrapper to get systemV working with Gnome applications so that is why I ask?

**Comment by nabijaczleweli** [comment]
Notionally, you could run this generator manually and hard-parse the exec lines. At some point you should ask yourself if it's just easier to use something that targets a traditional init tho. Or just write to sysfs manually.

**Comment by Raj2032** [comment]
@nabijaczleweli Hi, thanks for your response.

> traditional init tho

a traditional init would be runit?

**Comment by nabijaczleweli** [comment]
i mean, sure, runit is closer to commercial AT&T UNIX init than it is to systemd, but I'd still call it a bit of a stretch

**Comment by Raj2032** [comment]
@nabijaczleweli I see, are the tradiional init systems still maintained?
