### ISSUE TITLE
Will tmpfs use the swap space created by zram-generator?

### ISSUE THREAD

**Issue by daiaji** [systemd/zram-generator#173]
https://github.com/systemd/systemd/issues/12342

> I don't get it.
> 
> So there are two approaches:
> 
> 1.  Mount file system X as ramfs
> 2.  Mount file system X as tmpfs, but enable zswap?
> 
> It appears to me that option 2 is always the better approach, since tmpfs is backed by swappable memory anyway, and thus by enabing zswap you allow to the kernel freedom to choose what precisely to swap out or not, regardless if that's file system X or anything else. i.e. why make the link between compressed RAM backing and specific file systems explicit if you might as well make it implicit, and let the kernel choose what to swap out and what not?

https://wiki.archlinux.org/title/tmpfs

> [tmpfs](https://en.wikipedia.org/wiki/Tmpfs) is a temporary filesystem that resides in memory and/or swap partition(s). Mounting directories as tmpfs can be an effective way of speeding up accesses to their files, or to ensure that their contents are automatically cleared upon reboot.

It looks like the zram swap space generated by zram-generator should be usable by tmpfs.
Moreover, zram supports write-back devices, but zswap does not.

**Comment by nabijaczleweli** [comment]
tmpfs allocates from virtual memory, and [every](https://manpages.debian.org/unstable/manpages/tmpfs.5.en.html#VERSIONS) [source](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/tmpfs.rst?id=7bf70dbb18820b37406fdfa2aaf14c2f5c71a11a#n19) agrees. Not sure what the question is.
