### ISSUE TITLE
starting systemd times out

### ISSUE THREAD

**Issue by danielboston38** [systemd/zram-generator#185]
i am following the arch wiki to use zram-generator and enabling the systemd times out. im using the example conf file from the wiki and i added host-memory-limit = none.

**Comment by nabijaczleweli** [comment]
apparently arch wiki currently says

---
[zram-generator](https://github.com/systemd/zram-generator/blob/main/README.md) provides a `systemd-zram-setup@.service` unit to automatically initialize zram devices without users needing to [enable/start](https://wiki.archlinux.org/title/Enable/start) the template or its instances. See [zram-generator(8)](https://man.archlinux.org/man/zram-generator.8) and [zram-generator.conf(5)](https://man.archlinux.org/man/zram-generator.conf.5).

Before starting, permanently [disable zswap](https://wiki.archlinux.org/title/Zswap#Toggling_zswap) using the kernel parameter or sysctl knob. [[1]](https://github.com/systemd/zram-generator/issues/156)

Then, to create a zram swap device using `zstd` and half of the entire available ram, [install](https://wiki.archlinux.org/title/Install) [zram-generator](https://archlinux.org/packages/?name=zram-generator), then create `/etc/systemd/zram-generator.conf` with the following:
```
/etc/systemd/zram-generator.conf

[zram0]
zram-size = ram / 2
compression-algorithm = zstd
swap-priority = 100
fs-type = swap
```
Run [daemon-reload](https://wiki.archlinux.org/title/Daemon-reload), then [start](https://wiki.archlinux.org/title/Start) your configured `systemd-zram-setup@zramN.service` instance(s).

You can [check the swap status](https://wiki.archlinux.org/title/Swap#Swap_space) of your configured /dev/zramN devices by reading the [unit status](https://wiki.archlinux.org/title/Unit_status) of your `systemd-zram-setup@zramN.service` instance(s), or by using [zramctl(8)](https://man.archlinux.org/man/zramctl.8).

---

post content of `/etc/systemd/zram-generator.conf`, post what you're starting, post content of journal after you start it

**Comment by danielboston38** [comment]
sudo syztemctl start /dev/zram0.service, https://bpa.st/QGXA

**Comment by nabijaczleweli** [comment]
idk what to tell you. have you tried doing what the wiki says?

**Comment by danielboston38** [comment]
thats where im having the issue. i did  systemctl daemon-reload and then tried to start it and thats when im getting this issue.

**Comment by danielboston38** [comment]
so i guess this software is broken?

**Comment by regulator-g** [comment]
I had a similar issue, ended up making a bash script and using systemd to run it

its not that clear in the instructions but i think you need to disable zswap and enable the zram kernel module, try the steps listed here:
https://www.dwarmstrong.org/zram-swap/
