### ISSUE TITLE
Allow setting zram size through xenstore paths

### ISSUE THREAD

**Issue by Atrate** [systemd/zram-generator#197]
When using `zram` in a Xen DomU, it'd be nice if it'd be possible to use Xen's memory balooning parameters for setting the maximum RAM.

Talking especially about the 
```
/local/domain/$domain-id/memory/hotplug-max
```
parameter, as it controls the *actual* maximum amount of memory that a DomU can be assigned in Qubes OS specifically.

The parameter can be viewed with 
`xenstore-read /local/domain/$(xenstore-read domid)/memory/hotplug-max`.

**Comment by keszybz** [comment]
I guess this could be done, but it's also very specific. Is it really necessary to call `xenstore-read` twice to read this value?

Hmm, if anything, I think we might want to implement a function like "system" that'd allow arbitrary code to be called from an expression.  E.g.
```
zram-size = system('xenstore-read /local/domain/$(xenstore-read domid)/memory/hotplug-max') * 0.5
```

**Comment by nabijaczleweli** [comment]
fasteval supports custom functions (and strings AFAICT) so this is probably best

**Comment by nabijaczleweli** [comment]
No it doesn't, it only supports strings as parameters to `print()`. As in the parser says 
```rust
//! Value: Constant || UnaryOp || PrintFunc || StdFunc
//!
//! StdFunc: VarName((Expression,)*)?  ||  VarName[(Expression,)*]?
//!
//! PrintFunc: print(ExpressionOrString,*)
//!
//! ExpressionOrString: Expression || String
//!
//! String: ".*"
```
```rust
                    Bite(open_parenth) => {
                        // VarNames with Parenthesis are first matched against builtins, then custom.
                        match varname.as_ref() {
                            "print" => Ok(Bite(EPrintFunc(self.read_printfunc(slab,bs,depth,open_parenth)?))),
                            _ => Ok(Bite(EStdFunc(self.read_func(varname,slab,bs,depth,open_parenth)?))),
                        }
                    }
```

**Comment by keszybz** [comment]
Hmm, so maybe something like:
`set:<name> = <command>`, e.g.
`set:hotplug_max = xenstore-read /local/domain/$(xenstore-read domid)/memory/hotplug-max`
and then allow arbitrary shell command as `<command>`?

**Comment by nabijaczleweli** [comment]
Blegh, mixing random basically-free-form directives in with real keys with a strict vocabulary is kinda stinky to me.

How about accepting this *only* in the global section? So:
```
set:hotplug_max = xenstore-read /local/domain/$(xenstore-read domid)/memory/hotplug-max

[zram0]
zram-size = hotplug_max / 4

[zram1]
zram-size = hotplug_max / 16
```
We currently warn for any top-level key.

Then we can have all the top-level keys be `dir:arg = val` and strictly discriminate on `dir` only?

**Comment by nabijaczleweli** [comment]
Apparently
```
set:top = echo 3
```
gives us (not a joke): section=`None`, key=`"set"`, value=`"echo 3"`. Where did the top go? what the hell

**Comment by nabijaczleweli** [comment]
Took a while because the parser is too convoluted for its own good. #203
