### ISSUE TITLE
How to specify compression level?

### ISSUE THREAD

**Issue by guiopen** [systemd/zram-generator#199]
For example, we can set the compression algorithm to zstd by using:

compression-algorithm = zstd 

But zstd supports multiple compression levels, originally from 1 to 19, and now from -7 to 22 with caveats, but there is no mention about how we can change the compression level, can we just specify along the compression algorithm like this?:

compression-algorithm = zstd:1
Or
compression-algorithm = zstd:19

**Comment by nabijaczleweli** [comment]
I don't think this is true, since neither https://docs.kernel.org/admin-guide/blockdev/zram.html nor /sys/block/zram0 on bookworm/sid seem to have a control for level. Pretty sure that in this case, zstd is zstd and lz4 is lz4.

**Comment by guiopen** [comment]
So there is no way to specify compression level like we do with btrfs filesystem?

**Comment by nabijaczleweli** [comment]
ask on lkml if you want but i doubt anyone has wanted this before

**Comment by wommy** [comment]
got added in Oct
https://docs.kernel.org/admin-guide/blockdev/zram.html#set-compression-algorithm-parameters-optional
