### ISSUE TITLE
Manpage(s)?

### ISSUE THREAD

**Issue by nabijaczleweli** [systemd/zram-generator#22]
I [edited](https://github.com/nabijaczleweli/systemd-zram-generator.deb/blob/882f88da4ae0984d914e6d7de9d464245179ecc4/debian/systemd-zram-generator.8) a manpage from a different generator for my package because I felt bad packaging something with *no* manpage at all, but, well, something that's three lines long and doesn't document the config file (you could argue the [default config file](https://github.com/nabijaczleweli/systemd-zram-generator.deb/blob/53029c4e82fa48871ab437eefea993fd188c62de/debian/zram-generator.conf) is documentation enough I guess) is a step-down from the rest of systemd-adjacent documentation.

Quoth the Policy, [section 12.1 "Manual pages"](https://www.debian.org/doc/debian-policy/ch-docs.html):
> You should install manual pages in nroff source form, in appropriate places under /usr/share/man. You should only use sections 1 to 9 (see the FHS for more details). You must not install a pre-formatted “cat page”.
>
> Each program, utility, and function should have an associated manual page included in the same package. It is suggested that all configuration files also have a manual page included as well. Manual pages for protocols and other auxiliary things are optional.
>
> If no manual page is available, this is considered as a bug and should be reported to the Debian Bug Tracking System (the maintainer of the package is allowed to write this bug report themselves, if they so desire). Do not close the bug report until a proper man page is available.

I'm not sure (and, frankly, don't much care) about fedora policy, but fedora isn't crux, and apparently this is gonna be a Point of a subsequent release, so I'm assuming having some documentation would be nice.

I'd be open to writing said manpages myself, but I don't know what your preferred generator is/would be for this (my personal preference is `ronn`, which outputs [man(1)](https://rawcdn.githack.com/LoungeCPP/pir-8-emu/man/pir-8-emu.1) and [HTML](https://rawcdn.githack.com/LoungeCPP/pir-8-emu/man/pir-8-emu.1.html) pages from a [markdown dialect](https://github.com/LoungeCPP/pir-8-emu/blob/master/man/pir-8-emu.md)).

**Comment by keszybz** [comment]
> `ronn`, which outputs [man(1)](https://rawcdn.githack.com/LoungeCPP/pir-8-emu/man/pir-8-emu.1) and [HTML](https://rawcdn.githack.com/LoungeCPP/pir-8-emu/man/pir-8-emu.1.html) pages from a [markdown dialect](https://github.com/LoungeCPP/pir-8-emu/blob/master/man/pir-8-emu.md)

Sounds good. Having a source format that can be displayed natively by github is very nice.
