### ISSUE TITLE
generators should not write out anything but units

### ISSUE THREAD

**Issue by poettering** [systemd/zram-generator#26]
The generator writes out a drop-in for load-modules.d. Not OK, will break during daemon-reload.

As documented, please only generate unit files, nothing else.

https://github.com/systemd/zram-generator/blob/943d7aaf47a19c973310616cbd28b0e8f7455146/src/generator.rs#L53

**Comment by ignatenkobrain** [comment]
I think https://github.com/systemd/zram-generator/pull/25 is supposed to solve it.

**Comment by keszybz** [comment]
>  will break during daemon-reload

Why?

**Comment by nabijaczleweli** [comment]
For one, `systemd-modules-load.service` is `RemainAfterExit=yes`. Adding a module to `/run/modules-load.d` won't work after early boot (well, it didn't now that I tested it).

Additionally, quoth the manpage (emphasis mine):
> systemd-modules-load.service is an *early boot* service that loads kernel modules based on *static configuration*.

**Comment by keszybz** [comment]
Well, the man page is wrong here: modules are also loaded from /run. And service actually looks at the kernel command line to. So saying that it only reads "static" configuration is flat out wrong.

> Adding a module to /run/modules-load.d won't work after early boot (well, it didn't now that I tested it).

That's true. But when the generator is executed when systemd initially starts, we know that it'll run before any units, so it'll work reliably in this case.

So the dependency on modules-load.service doesn't fully solve the issue, it should work reliably during normal boot.

**Comment by nabijaczleweli** [comment]
Point.

The problem remains, though: we need to load zram.ko at a deterministic time (before leaving the generator, so we can make the devices) anyway, and depending on sd-modules-load afterward is pointless.

**Comment by lucab** [comment]
Pardon me if this is a silly question: why is this "zram configuration" logic a systemd generator? It seems to have some intrinsic dependencies on other components (e.g. modules-load and modprobe configuration) so perhaps it may benefit from scheduling as part of the normal graph of units?

(I went back in git history and github tickets but didn't find any conclusive answer, perhaps this was covered in some ML or other project and I missed it)

**Comment by keszybz** [comment]
It's a generator because this is similar to how we handle swaps and mounts in general, for example `systemd-fstab-generator`. Running as a generator we know that we'll be early enough to do things like generate unit or modules-load.d snippets. I think we can figure out a solution to the modprobe issues without changing the paradigm. But if if turns out to be impossible, or there are other reasons, the generator could be replaced by an early-boot service too.

As to the other reasons: one thing that came up is the possibility to set up zswap if there are any physical swap devices, and zram if there are none. Right now, this is pretty hard, because swap devices can be "declared" by a few different mechanisms: fstab, gpt-auto-discovery, and static .swap units at least. At the time when the generator is running, it is unknown whether any swap devices will be discovered. Running as a service during boot would allow us to handle this fairly easy.

**Comment by poettering** [comment]
> > will break during daemon-reload
> 
> ~Why?~ How?

generators are designed so that whatever they generate is automatically removed on "daemon-reload". i.e. they translate external config into native config, and that translation goes away on "daemon-reload" so that the data is re-translated whenever PID1 is reloaded. This doesn#t work for anything but unit files. And I think that's the right behaviour. If you generate config for other tools then such a generator should be bound to that other tool's lifecycle really. This is briefly documented in "systemd.generator(7)", btw, in the "Notes about writing generators" section.

Quite frankly I am puzzled you need to load modules explicitly anyway. This smells like a bug in the zram module. Doesn't it carry module metadata enough so that udev can pre-create the devices so that the module is autoloaded when needed?

Manual, explicit module loading should not be necessary today, except for broken drivers.

**Comment by poettering** [comment]
i.e. the zram kmod really should be fixed to implement the modalias stuff so that `/run/tmpfiles.d/static-nodes.conf` can do its thing.

**Comment by poettering** [comment]
omg, the "hot_add" feature of that module is so broken. oh man, are you sure the kernel part is ready for prime time? the userspace-facing API is very 90's...

**Comment by keszybz** [comment]
Anyway, #25 removed the modprobe dropin, so this can be closed.
