### ISSUE TITLE
To make swap, maybe use systemd-mkfs@.service

### ISSUE THREAD

**Issue by poettering** [systemd/zram-generator#27]
https://github.com/systemd/zram-generator/blob/943d7aaf47a19c973310616cbd28b0e8f7455146/src/setup.rs#L43

Maybe use systemd-mkfs@.service for formatting the swap device, and ordering it before the .swap device? it can format swap partitions too, and nowadays locks properly around it...

**Comment by ignatenkobrain** [comment]
@poettering you meant `systemd-mkswap@device.service`?

**Comment by nabijaczleweli** [comment]
This would make zram-generator depend on systemd's repart feature, which is disabled by some distributions (notably Debian and derivatives thereof).

I don't think depending on another service (which may or may not be there and will fail cryptically, as it had for me in my tests on sid) => running another executable => execing mkswap is really worthwhile replacing execing mkswap ourselves.

**Comment by keszybz** [comment]
Would there be much advantage over calling `/usr/lib/systemd/systemd-makefs swap ...` from our own unit? I'm not particularly keen on using `systemd-mkswap@device.service` because the mode will be different for zwap, and then there'd be asymmetry between the two paths.

**Comment by poettering** [comment]
> This would make zram-generator depend on systemd's repart feature, which is disabled by some distributions (notably Debian and derivatives thereof).

Hmm, wa? It's not really related to that. Those are different tools. I am not sure why Debian would turn off either, sounds unnecessary, but in particular turning off "systemd-makefs" is really pointless, it just makes the "x-systemd.growfs" mount option not work, and who wins by that?

**Comment by poettering** [comment]
> I don't think depending on another service (which may or may not be there and will fail cryptically, as it had for me in my tests on sid) => running another executable => execing mkswap is really worth the added complexity (run-time and logical) of replacing execing mkswap ourselves.

Well, proper locking with https://systemd.io/BLOCK_DEVICE_LOCKING is kinda a good thing, because it means your stuff will actually work, and not just be a racy excercise of will it won't it...

**Comment by nabijaczleweli** [comment]
You're right, the sd-makefs binary exists, but depending on `systemd-mkswap@.service` didn't do much. Perhaps I was holding it wrong.

@keszybz's suggestion worked for me though.
