### ISSUE TITLE
Document installation ways for various distributions

### ISSUE THREAD

**Issue by Prototik** [systemd/zram-generator#28]
It would be nice if README contains ways to obtain zram-generator for various OSes.

I can start this list with my packages for ArchLinux (in AUR repository):  
[zram-generator](https://aur.archlinux.org/packages/zram-generator/) - latest release  
[zram-generator-git](https://aur.archlinux.org/packages/zram-generator-git/) - latest git commit

Any other packages exists for now?

**Comment by keszybz** [comment]
https://src.fedoraproject.org/rpms/rust-zram-generator in Fedora.

**Comment by nabijaczleweli** [comment]
I have a `systemd-zram` package in my Debian repository @ https://debian.nabijaczleweli.xyz/README.
