### ISSUE TITLE
configuration fragments and vendor defaults

### ISSUE THREAD

**Issue by lucab** [systemd/zram-generator#29]
First of all, thanks for pushing this forward!

It looks like this component may be soon landing in several distro, including possibly Fedora 33. We briefly touched this topic for Fedora CoreOS at https://github.com/coreos/fedora-coreos-tracker/issues/509, and the initial consensus seems to be to ship the component but in a non-active state, showing users how to opt-in via first-boot configuration.

For that to work best, I think we are interested in having this TODO item tackled:
https://github.com/systemd/zram-generator/blob/943d7aaf47a19c973310616cbd28b0e8f7455146/TODO#L3

We already have a Rust library taking care of fragment scanning at https://docs.rs/liboverdrop and I can help porting the current monolithic configuration to a overlay+fragments approach. That would help shipping this project while keeping distribution defaults separate from user and runtime configuration.

@keszybz can you please expand here the TODO line above with a bit more details regarding expected paths, file names and content, merging strategy, etc? That would hopefully shorten the review-rework cycle in order to land support for this.

**Comment by ignatenkobrain** [comment]
I think `/usr/lib/systemd/zram-generator.conf` + `/etc/systemd/zram-generator.conf`. But probably it would make sense to create `.d` directories, not sure.

**Comment by lucab** [comment]
Oh, sorry, I did not detail that clearly enough. I'm indeed interested in seeing fragments support from `.d` directories as part of this (but I don't know how the current monolithic config file plays into that).

**Comment by cmurf** [comment]
If I understand correctly: no config in /usr indicates disabled by default, where properly formatted config in /usr indicates enabled by default. And then a config in /etc indicates override. So if enabled by default, merely `touch /etc/systemd/zram-generator.conf` (or `.d` equivalent) would make it disabled, or for that matter `/run` in case `/etc` is immutable?

I have no problem with it, and also consider it a soft blocker on the feature, consistent with Lennart's [comment](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/4QUI4XVTWXKCNEO47CE2S2R67ZZTVXMC/) in the devel thread (middle of the comment).

**Comment by Prototik** [comment]
Would be nicer to have `/etc/systemd/zram-generator.conf` symlinked to `/dev/null` as disabled marker? It would be similar to systemd's approach too.

**Comment by keszybz** [comment]
liboverdrop seems nice. I'll whip up a patch.

**Comment by keszybz** [comment]
The Change pages states that the generator can be disabled by removing `/etc/systemd/zram-generator.conf`, which is not going to be permanent if the rpm ships this file, because it'll be reinstalled on upgrade if removed. So yeah, we should change this now.

**Comment by lucab** [comment]
@keszybz do you plan to 1) only use monolithic config files (i.e. `zram-generator.conf` in usr+run+etc) 2) only use fragments in `.d` directories 3) use both at the same time?

For Fedora CoreOS specific usecase it would be great to have a setup like:
 * `/usr/[...].d/10-fedora-default-zram0.conf` shipped in Fedora RPM to enable the default behavior
 * `/usr/[...].d/10-coreos-disable-zram0.conf` to opt-out the default zram0 setup (this possibly needs a per-device `enable: bool` knob, and logic to merge config entries)
 * a user-configured `/etc/[...].d/55-enable-zram0.conf` (or a null-symlink) to re-enable zram0

**Comment by keszybz** [comment]
>  3) use both at the same time?

Both. I find it easiest to duplicate the logic that is used in systemd in full and not think about it too much. The flexibility will be overkill in this case, but it doesn't hurt.

> `/usr/[...].d/10-coreos-disable-zram0.conf` to opt-out the default zram0 setup (this possibly needs a per-device `enable: bool` knob, and logic to merge config entries)

Merging entries and masking of dropins should work with the PR I'm about to submit. There is no know to disable an entry, but setting `host-memory-limit=0` would have the same effect. The knob can be trivially added if you want.
