### ISSUE TITLE
Tests can't be run in the build env

### ISSUE THREAD

**Issue by ignatenkobrain** [systemd/zram-generator#36]
In Fedora, the build environment is basically a chroot (or nspawn) so it is either can be detected as container in which case devices won't be created and tests will fail or modprobe zram will fail. Another thing that can go wrong is that systemd-detect-virt is not installed, so we probably should replace that part to return false instead of erroring out.

**Comment by ignatenkobrain** [comment]
I've did this, but it is horrible:

```diff
diff --git a/src/generator.rs b/src/generator.rs
index f730943..48c4957 100644
--- a/src/generator.rs
+++ b/src/generator.rs
@@ -25,6 +25,9 @@ fn make_symlink(dst: &str, src: &Path) -> Result<()> {
 }
 
 fn virtualization_container() -> Result<bool> {
+    if std::env::var("TEST").unwrap_or("0".to_string()).as_str() != "0" {
+        return Ok(false);
+    }
     match Command::new("systemd-detect-virt")
         .arg("--quiet")
         .arg("--container")
@@ -51,7 +54,8 @@ pub fn run_generator(devices: &[Device], output_directory: &Path) -> Result<()>
             .iter()
             .map(|dev| handle_device(output_directory, dev)),
     )?;
-    if !devices_made.is_empty() {
+    if std::env::var("TEST").unwrap_or("0".to_string()).as_str() == "0" && !devices_made.is_empty()
+    {
         /* We created some devices, let's make sure the module is loaded and they exist */
         if !Path::new("/sys/class/zram-control").exists() {
             Command::new("modprobe")
```

**Comment by nabijaczleweli** [comment]
If anything, this means that this is working as intended :Р

Spoofing `sd-detect-virt` should be as simple as `ln -s /bin/true systemd-detect-virt && PATH=".:$PATH" cargo test`.

Do you have root in the environment? If so, chrooting to some random folder or bind-mounting a piece of `/tmp` over (parts of?) `/sys` should work.
