### ISSUE TITLE
RFE: parse boot parameters for an Anaconda inbibit parameter

### ISSUE THREAD

**Issue by cmurf** [systemd/zram-generator#42]
Currently Anaconda has its own built-in swap-on-zram implementation, which can be inhibited by 'inst.zram'. Since the plan is for that implementation to be obsoleted in favor of zram-generator, it might be nice to keep this option functional.

Igor's idea is for the generator to parse for 'inst.zram' or 'inst.nozram' and simply inhibit. And have anaconda requires 'zram-generator-defaults' so that it can by default depend on swap-on-zram being available *unless* inhibited by this option. That seems more elegant than my idea that Anaconda go to the trouble of stopping the service created by the generator.
https://www.redhat.com/archives/anaconda-devel-list/2020-July/msg00016.html

**Comment by poncovka** [comment]
Just a note, Anaconda supports the following variants:

```
inst.zram
inst.zram=on
inst.zram=1
```
It forces usage of zRAM swap for the installation process.

```
inst.zram=off
inst.zram=0
```

It disables usage of zRAM swap for the installation process.

I don't think that we support `inst.nozram` at this moment.

**Comment by keszybz** [comment]
I'm confused which way `zram-generator` is supposed to go: should `inst.zram` **inhibit** `zram-generator` units?

**Comment by keszybz** [comment]
Please check if #43 does what you need.

**Comment by cmurf** [comment]
Anaconda folks have decided to deprecate the inst.zram toggle. There may be some other use case to inhibit (troubleshooting?) via command line, but for now I'll close this issue.
https://www.redhat.com/archives/anaconda-devel-list/2020-July/msg00025.html
