### ISSUE TITLE
service unit fails when host-memory-limit is set below the host memory

### ISSUE THREAD

**Issue by cmurf** [systemd/zram-generator#44]
Summary: Ideally this would not cause the service unit to fail outright, but just note that it's ignoring or skipping the setup and exit. 

The reason is if any edition/spin in Fedora decides to ship their own defaults, using host-memory-limit, it can result in cases where the unit fails by default. And that's usually considered a release blocking violation: All system services present after installation with one of the release-blocking package sets must start properly, unless they require hardware which is not present. 

Did it start properly? I guess so, in which case it could be argued that the current behavior is intentional.

zram-generator-0.2.0-1.fc33.x86_64

`cat /proc/meminfo` 
MemTotal:        8018900 kB

`cat /etc/systemd/zram-generator.conf`
```
[zram0]
host-memory-limit = 7000
zram-fraction = 1.0
max-zram-size = 6000
compression-algorithm = lzo-rle
```

`systemctl restart swap-create@zram0.service`

Service unit fails:
```
Jul 21 17:13:46 fmac.local systemd[1]: Starting Create swap on /dev/zram0...
Jul 21 17:13:46 fmac.local systemd[1]: swap-create@zram0.service: Main process exited, code=exited, status=1/FAILURE
Jul 21 17:13:46 fmac.local zram-generator[4140]: Error: Failed to configure disk size into /sys/block/zram0/disksize
Jul 21 17:13:46 fmac.local zram-generator[4140]: Caused by:
Jul 21 17:13:46 fmac.local zram-generator[4140]:     Invalid argument (os error 22)
Jul 21 17:13:46 fmac.local systemd[1]: swap-create@zram0.service: Failed with result 'exit-code'.
Jul 21 17:13:46 fmac.local systemd[1]: Failed to start Create swap on /dev/zram0.
```

`dmesg`
```
[ 3616.983601] zram_generator::config[4140]: zram0: system has too much memory (7830MB), limit is 7000MB, ignoring.

```

**Comment by nabijaczleweli** [comment]
Okay, but why is that unit being started in the first place? The disksize is 0 (which is the cause of the "Invalid argument" error), which means that it wasn't linked to `swap.target.wants` in the generation step, and starting the unit manually is the administrator's fault.

**Comment by nabijaczleweli** [comment]
This is equivalent to an error you'd get [starting a unit for an unmentioned device](https://github.com/systemd/zram-generator/blob/ff4fb9b51e256b6543485be59d6ec5cdf7228739/src/setup.rs#L22), though, admittedly, with a different error message.

**Comment by keszybz** [comment]
> Okay, but why is that unit being started in the first place?

One way is to edit the configuration and try to start the unit without running `daemon-reload`.

**Comment by nabijaczleweli** [comment]
Well, yeah, but then the unit behaves as would be expected, taking the current config, and failing, since the device no longer exists. This is equivalent to force-starting any random device and expecting it to "work" (do something not in the config).

**Comment by nabijaczleweli** [comment]
Though something like
```rust
if device.disksize == 0 {
    return Err(anyhow!("Device {} no longer configured, did you forget to daemon-reload?", device_name));
}
```
would save a headache or two down the line

**Comment by cmurf** [comment]
You're right - my assumption that unit restart is the same as rebooting is invalid. I'll retest.

**Comment by cmurf** [comment]
Confirmed. The 'unit restart' test after changing configuration is simply an invalid test. This is not a bug.

Following reboot, this is the result I expect. The unit is not failed.
```
[chris@localhost ~]$ sudo journalctl -b | grep zram
Jul 22 12:08:04 localhost.localdomain zram_generator::config[492]: zram0: system has too much memory (1951MB), limit is 1024MB, ignoring.
Jul 22 12:08:04 localhost.localdomain zram_generator::generator[492]: No devices configured, exiting.
[chris@localhost ~]$ 
```

**Comment by nabijaczleweli** [comment]
FWIW, to get a clean(er) test environment, you should be able to do something like `systemctl stop swap.target && systemctl daemon-reload && systemctl start swap.target`
