### ISSUE TITLE
Problem enabling zstd

### ISSUE THREAD

**Issue by darkdragon-001** [systemd/zram-generator#50]
I tried to use `zstd` compression with zram on Fedora 33 with kernel `5.8.14-300.fc33.x86_64`.

    # /etc/systemd/zram-generator.conf
    [zram0]
    compression-algorithm = zstd

Restarting via `sudo systemctl restart swap-create@zram0.service` gives me the following error:
```
Okt 09 16:12:03 localhost.localdomain systemd[1]: Starting Create swap on /dev/zram0...
Okt 09 16:12:03 localhost.localdomain kernel: Can't allocate a compression stream
Okt 09 16:12:03 localhost.localdomain kernel: zram: Cannot initialise zstd compressing backend
Okt 09 16:12:03 localhost.localdomain zram-generator[3938]: Error: Failed to configure disk size into /sys/block/zram0/disksize
Okt 09 16:12:03 localhost.localdomain zram-generator[3938]: Caused by:
Okt 09 16:12:03 localhost.localdomain zram-generator[3938]:     Cannot allocate memory (os error 12)
Okt 09 16:12:03 localhost.localdomain systemd[1]: swap-create@zram0.service: Main process exited, code=exited, status=1/FAILURE
```
I also tried rebooting and the same problem occurs.

```
$ cat /sys/block/zram0/comp_algorithm
lzo [lzo-rle] lz4 lz4hc 842 zstd
```

What is going on? Any help appreciated!

**Comment by nabijaczleweli** [comment]
Does this also happen when you run this as root?
```sh
modprobe -r zram
modprobe zram
echo 1 > /sys/block/zram0/reset
echo zstd > /sys/block/zram0/comp_algorithm
echo $NUMBER > /sys/block/zram0/disksize
/usr/lib/systemd/systemd-makefs swap /dev/zram0
```
(Substitute `$NUMBER` for your desired disksize, of course.)

**Comment by darkdragon-001** [comment]
@nabijaczleweli Thanks for your help! `modprobe zram` solved the problem (which I persisted across reboots via `/etc/modules-load.d/`). I was just confused because I use btrfs with zstd compression for my root filesystem (from which the systemd config files are loaded) - obviously this doesn't need the additional kernel module...

**Comment by keszybz** [comment]
Since aa03047eec6df8cee8d9b11cdfc1f64a19a8f140 (which is included in the zram-generator version in F33, 0.2.0), we do `modprobe zram` internally. So loading `zram` should be a noop and shouldn't really change anything. One explanation would be that selinux is preventing the modprobe from being done from the generator. Please check if you had any avcs.

**Comment by darkdragon-001** [comment]
When I remove the manual module loading, it seems to be still working. Thanks for your help!

**Comment by keszybz** [comment]
@darkdragon-001 if you could provide the debug information that the kernel devs requested in https://bugzilla.kernel.org/show_bug.cgi?id=211173, that'd be super cool.
