### ISSUE TITLE
How to disable zram-generator?

### ISSUE THREAD

**Issue by polarathene** [systemd/zram-generator#68]
I am aware of stopping a specific zram device `systemctl stop systemd-zram-setup@zram0.service` or using `mask` instead of `stop`, and that I can also comment out entries in config. But the generator service as a whole, it's unclear how to disable this from running during `systemctl daemon-reload` or startup, where it's clearly still running due to `dmesg` logs.

**Comment by nabijaczleweli** [comment]
[`zram-generator.conf(5)`](https://github.com/systemd/zram-generator/blob/main/man/zram-generator.conf.md#configuration-directories-and-precedence) says: 
> The generator understands the following option on the kernel command-line: `systemd.zram[=0|1]`. When specified with a true argument (or no argument), the `zram0` device will be created. Default options apply, but may be overridden by configuration on disk if present. When specified with a false argument, no zram devices will be created by the generator. This option thus has higher priority than the configuration files.

**Comment by polarathene** [comment]
This does not answer my question... This isn't about a kernel param, `systemctl daemon-reload` or `systemctl restart swap.target` trigger this project. It doesn't appear to have a service that can be disabled.

I guess I just remove it from the location it was installed in? (built from git, not via package manager)

**Comment by nabijaczleweli** [comment]
indeed
