### ISSUE TITLE
path is not absolute, ignoring

### ISSUE THREAD

**Issue by artelkr** [systemd/zram-generator#75]
Hi,

I have this error in journalctl

`/run/systemd/generator/var-tmp.mount:11: Where= path is not absolute, ignoring: "/var/tmp"`

```shell
$ cat /run/systemd/generator/var-tmp.mount
# Automatically generated by /usr/lib/systemd/system-generators/zram-generator

[Unit]
Description=Compressed Storage on /dev/zram1
Documentation=man:zram-generator(8) man:zram-generator.conf(5)
Requires=systemd-zram-setup@zram1.service
After=systemd-zram-setup@zram1.service

[Mount]
What=/dev/zram1
Where="/var/tmp"

```

```shell
$ cat /etc/systemd/zram-generator.conf | tail -n 4 

# Where to mount the file system. If a mount point is not specified,
# the device will be initialized, but will not be used for anything.
mount-point = /var/tmp

```

/dev/zram1 is not used according to zramctl, it stuck on 1,4M

Or i don't understand how it's supposed to work?

**Comment by rathann** [comment]
I'm getting the same message:
```
Aug 03 20:50:40 systemd[1]: /run/systemd/generator/var-lib-mock.mount:11: Where= path is not absolute, ignoring: "/var/lib/mock"
```
with this `/etc/systemd/zram-generator.conf`:
```
[zram0]
zram-fraction = 0.5
max-zram-size = 4096

[zram1]
mount-point = /var/lib/mock
zram-fraction = 0.75
max-zram-size = 12288
```
The generated unit is:
```
# Automatically generated by /usr/lib/systemd/system-generators/zram-generator

[Unit]
Description=Compressed Storage on /dev/zram1
Documentation=man:zram-generator(8) man:zram-generator.conf(5)
Requires=systemd-zram-setup@zram1.service
After=systemd-zram-setup@zram1.service

[Mount]
What=/dev/zram1
Where="/var/lib/mock"
```
It looks like the code in [src/generator.rs#L287](https://github.com/systemd/zram-generator/blob/main/src/generator.rs#L287) is adding extra quotes which systemd doesn't seem to like. I traced it to this config parsing code in [src/config.rs#L245](https://github.com/systemd/zram-generator/blob/main/src/config.rs#L245), but without knowing Rust, I have no idea how to fix this.
@keszybz , this looks simple to fix.

**Comment by rathann** [comment]
Thanks, @keszybz !
