### ISSUE TITLE
configuration file defaults

### ISSUE THREAD

**Issue by cmurf** [systemd/zram-generator#9]
The configuration file uses "memory-limit" value to mean something other than /sys/block/zram0/mem_limit - and that's confusing. 

There's no point in limiting zram-generator to small RAM devices. It's actually especially useful for systems with huge amounts of RAM, 64G or 128G, to give them a small amount of swap, instead of either no swap, or a huge swap partition on a drive (e.g. the anaconda default).

1. I think memory-limit should either be deprecated or set to none by default.

2. Ratio should default to 0.5. Upstream suggests up to 2x RAM is reasonable, due to 2:1 compression ratio expected there's no point in going above this.

3. A new setting: max-zram-size, is set to 4G by default.

The effect of all three is: if /etc/systemd/zram-generator.conf exists, create a zram device sized at 1:2 to RAM, up to a max of 4G.

I think this is more consistent with how distributions and end users will want to use this, out of the box. Or if anything, increase the ratio to 1:1 with RAM. That's what I've been doing for all of my crazy tests and it's fine. Better than swap on HDD or SSD.

**Comment by keszybz** [comment]
Yeah.

Do you have any opinion on the default compression algorithm? I'd expect zstd to be better than the default.

**Comment by cmurf** [comment]
Difficult to assess. I've only assessed 128K block size for Btrfs and zstd:1 is all around pretty awesome. But it might be expensive for ARM, and not as great for 4K pages? I'm not sure what the block size would be? The change for Fedora will affect all arches so that's a consideration.

lzbench does not have lzo-rle either, and I suspect rle would be super cheap for lots of zeros, and that might be really common for anonymous page evictions? I haven't studied this. It will surely depend on the workload.

This is on ARM (Pi Zero):
```
$ ./lzbench -v -b4 -c2 -ezstd,1,3/lz4/lzo/ -m400 ~/silesia.tar
Compressor name         Compress. Decompress.  Orig. size  Compr. size  Ratio Filename
memcpy                    298 MB/s   337 MB/s   104857600    104857600 100.00 /home/chris/silesia.tar
zstd 1.4.4 -1              10 MB/s    24 MB/s   104857600     37461989  35.73 /home/chris/silesia.tar part 1
zstd 1.4.4 -3            3.78 MB/s    23 MB/s   104857600     36984842  35.27 /home/chris/silesia.tar part 1
lz4 1.9.2                  36 MB/s    62 MB/s   104857600     52474722  50.04 /home/chris/silesia.tar part 1
lzo1 2.10 -1               28 MB/s    68 MB/s   104857600     52209718  49.79 /home/chris/silesia.tar part 1
```

This is on a recent intel laptop
```
[chris@flap lzbench]$ ./lzbench -v -b4 -c2 -ezstd,1,3/lz4/lzo/ ~/silesia.tar
Compressor name         Compress. Decompress. Compr. size  Ratio Filename
memcpy                   7054 MB/s  7156 MB/s   211947520 100.00 /home/chris/silesia.tar
zstd 1.4.4 -1             156 MB/s   421 MB/s    91475648  43.16 /home/chris/silesia.tar
zstd 1.4.4 -3             120 MB/s   406 MB/s    89891801  42.41 /home/chris/silesia.tar
lz4 1.9.2                 430 MB/s  2410 MB/s   122717358  57.90 /home/chris/silesia.tar
lzo1 2.10 -1              204 MB/s   470 MB/s   121247699  57.21 /home/chris/silesia.tar
```

Too bad no lzo-rle in this set. I'd say lz4 or lzo-rle. Using lzo-rle I'm getting 4:1 to 3:1 ratios fairly consistently with a lot of workloads, esp web page stuff. And 3:1 to 2:1 for compiling. I bet a more "complex" workload does better and faster with lz4. The generic case is probably better with lzo-rle. At least until proven otherwise.

I think zstd is too expensive for this case at least compared to memcpy. This test may be 100% flawed for all I know.

This is the corpus or "workload" and even that is open for question.
http://sun.aei.polsl.pl/~sdeor/index.php?page=silesia

**Comment by Maryse47** [comment]
> Ratio should default to 0.5. Upstream suggests up to 2x RAM is reasonable, due to 2:1 compression ratio expected there's no point in going above this.

You didn't provide reason why 0.5 is better than 0.25 especially as it's higher than recommended range.

> The generic case is probably better with lzo-rle. At least until proven otherwise.

Your own testing proved lz4 is better although I would use a tool specifically [suited for the job](https://github.com/sergey-senozhatsky/zram-perf-test)

**Comment by keszybz** [comment]
> You didn't provide reason why 0.5 is better than 0.25 especially as it's higher than recommended range.

0.5 is better because it means that the user will see (assuming 3:1 compression ratio) an effective memory of 0.5 × R ×1 + 0.5 × R × 3 = 2R, where R is the physical RAM size. 0.5 is still low enough that we can be fairly sure that there won't be any artificial oom in the kernel. 0.75 would probably be even better, but maybe let's remain a bit more conservative for now.

> Your own testing proved lz4 is better

Yeah, good, but not unequivocally better. In general I'd prefer for the kernel to set the best default here. After all, they are in the best position to know which choice is the most performant for some architecture and some version of the underlying implementation. If the difference was more pronounced, we could override it, but based on those results, I think it's best to keep the default for now.

**Comment by Maryse47** [comment]
> In general I'd prefer for the kernel to set the best default here.

From my observations kernel developers only change defaults long time **after** consensus about best default is established among users. You know, it's like Ent council...

I believe lz4 is most popular option as seen in default setting in similar projects.

**Comment by cmurf** [comment]
I have no objection to eiher lz4 or lzo-rle. I've used both for months at a time. And Fedora IoT has been using lz4 for years in production. But with fairly consistent 4:1 and 3:1 ratios with lzo-rle, with the workload being loading random webpages in Firefox and compiling webkitgtk and the kernel, I have to think a decent portion of my anonymous pages have zeros in them, and are being very cheaply compressed by the rle component. So unfortunately we don't really know, it's a coin toss.

I did look at zram-perf-test. I got it to build on Fedora, but the tests fail, and I wasn't able to figure out why. Of course, like any synthetic benchmarking tool, it may be useful to find weird edge cases, but it is only as valid as the workload it simulates. If it's not simulating the workloads we care about in the default case across the variety of products, it might not be that helpful. And I certainly put my own lzbench test with the silesia corpus in this category.

**Comment by cmurf** [comment]
BTW I did hear from some CoreOS and cloud folks that they might actually consider leveraging the memory-limit setting, where they enable for small memory setups, and stick with no swap at all for setups that have heftier provisioning. I still think "none" for upstream default makes sense.
